from buildcompiler.domain import (
    ApprovalStatus,
    BuildRequest,
    BuildStage,
    BuildStatus,
    BuildWarning,
    DesignKind,
    MissingBuildInput,
    RequiredApproval,
    StageResult,
    StageStatus,
)


def test_enum_values_and_planned_stages():
    assert StageStatus.BLOCKED.value == "blocked"
    assert StageStatus.FAILED.value == "failed"
    assert BuildStatus.SUCCESS.value == "success"
    assert BuildStage.ASSEMBLY_LVL1.value == "assembly_lvl1"
    assert BuildStage.DOMESTICATION.value == "domestication"
    assert BuildStage.ASSEMBLY_LVL2.value == "assembly_lvl2"
    assert BuildStage.TRANSFORMATION.value == "transformation"
    assert BuildStage.PLATING.value == "plating"


def test_blocked_vs_failed_semantics_are_documented_as_contract_data():
    blocked = MissingBuildInput(
        source_stage=BuildStage.ASSEMBLY_LVL1,
        source_design_identity="sbol://design/x",
        missing_identity="sbol://part/y",
        missing_display_id="y",
        missing_kind="cds",
        required_stage=BuildStage.DOMESTICATION,
        reason="Input could be generated by upstream stage",
    )
    failed = MissingBuildInput(
        source_stage=BuildStage.ASSEMBLY_LVL1,
        source_design_identity="sbol://design/x",
        missing_identity="sbol://part/z",
        missing_display_id="z",
        missing_kind="cds",
        required_stage="fatal",
        reason="Unsupported design cannot proceed without changes",
    )

    assert blocked.required_stage != "fatal"
    assert failed.required_stage == "fatal"


def test_default_mutables_are_isolated_across_instances():
    req1 = BuildRequest(
        "r1", BuildStage.DOMESTICATION, "a", None, DesignKind.COMPONENT_DEFINITION
    )
    req2 = BuildRequest(
        "r2", BuildStage.DOMESTICATION, "b", None, DesignKind.COMPONENT_DEFINITION
    )
    req1.constraints["x"] = 1
    assert req2.constraints == {}

    s1 = StageResult("s1", BuildStage.DOMESTICATION, StageStatus.SUCCESS)
    s2 = StageResult("s2", BuildStage.DOMESTICATION, StageStatus.SUCCESS)
    s1.request_ids.append("r1")
    s1.products.append(object())
    s1.missing_inputs.append(
        MissingBuildInput(
            BuildStage.DOMESTICATION, "a", "b", None, "promoter", "fatal", "missing"
        )
    )
    s1.required_approvals.append(
        RequiredApproval(ApprovalStatus.REQUIRED, "biosafety", "needed")
    )
    s1.warnings.append(BuildWarning("warn", "msg"))
    s1.protocol_artifacts["x"] = "y"
    s1.logs.append("log")

    assert s2.request_ids == []
    assert s2.products == []
    assert s2.missing_inputs == []
    assert s2.required_approvals == []
    assert s2.warnings == []
    assert s2.protocol_artifacts == {}
    assert s2.logs == []

    a1 = RequiredApproval(ApprovalStatus.REQUIRED, "biosafety", "needed")
    a2 = RequiredApproval(ApprovalStatus.APPROVED, "biosafety", "granted")
    a1.metadata["id"] = "1"
    assert a2.metadata == {}

    w1 = BuildWarning("w1", "warning")
    w2 = BuildWarning("w2", "warning")
    w1.metadata["code"] = "X"
    assert w2.metadata == {}
