"""Emit standalone Python with literal data and a closed set of SDK methods."""

import keyword
import math

from buildcompiler.protocols.attribution import PUDU_LICENSE
from buildcompiler.protocols.backends.opentrons.program import (
    Call,
    OpentronsProgram,
    Record,
    Reference,
    SetStartingTip,
)

METHODS = frozenset(
    {
        "load_module",
        "load_labware",
        "load_instrument",
        "define_liquid",
        "load_liquid",
        "pick_up_tip",
        "drop_tip",
        "mix",
        "aspirate",
        "dispense",
        "distribute",
        "blow_out",
        "touch_tip",
        "open_lid",
        "close_lid",
        "set_temperature",
        "set_block_temperature",
        "set_lid_temperature",
        "deactivate",
        "execute_profile",
        "comment",
        "move_labware",
    }
)


def _literal(value: object) -> str:
    if isinstance(value, Reference):
        expression = f"resources[{value.name!r}]"
        if value.well is not None:
            expression += f"[{value.well!r}]"
        if value.bottom_mm is not None:
            expression += f".bottom({_literal(value.bottom_mm)})"
        if value.top_mm is not None:
            expression += f".top({_literal(value.top_mm)})"
        if value.track_conical_height:
            expression = f"_conical_source({expression})"
        return expression
    if isinstance(value, Record):
        return (
            "{"
            + ", ".join(f"{key!r}: {_literal(item)}" for key, item in value.entries)
            + "}"
        )
    if isinstance(value, tuple):
        return "[" + ", ".join(_literal(item) for item in value) + "]"
    if value is None or type(value) in (str, bool, int):
        return repr(value)
    if type(value) is float and math.isfinite(value):
        return repr(value)
    raise TypeError(f"Unsupported program literal: {type(value).__name__}")


def render_python(program: OpentronsProgram, *, name: str) -> str:
    """Return source; importing or calling this function performs no SDK work."""
    metadata = {
        "protocolName": name,
        "author": "BuildCompiler",
        "apiLevel": program.api_level,
    }
    lines = [
        *(f"# {line}" for line in PUDU_LICENSE.splitlines()),
        "# Generated by BuildCompiler. Protocol behavior derived from PUDU (MIT).",
        "from opentrons import protocol_api",
        "",
        f"metadata = {metadata!r}",
        "",
        "def _conical_source(well):",
        "    # PUDU SmartPipette's conical-tube policy; requires API liquid tracking.",
        "    try:",
        "        volume = well.current_liquid_volume()",
        "        if volume is None or volume < well.max_volume * 0.2:",
        "            return well",
        "        return well.bottom(max((volume / well.max_volume) * (well.depth - 10) - 10, 3))",
        "    except Exception:",
        "        return well",
        "",
        "def run(protocol: protocol_api.ProtocolContext):",
        "    resources = {'protocol': protocol, 'OFF_DECK': protocol_api.OFF_DECK}",
    ]
    wells = dict(program.wells)
    for instruction in program.instructions:
        if isinstance(instruction, SetStartingTip):
            lines.append(
                f"    resources[{instruction.pipette!r}].starting_tip = {_literal(instruction.tip)}"
            )
            continue
        if not isinstance(instruction, Call) or instruction.method not in METHODS:
            raise ValueError("Unsupported SDK instruction.")
        arguments = [_literal(value) for value in instruction.args]
        for key, value in instruction.kwargs:
            if not key.isidentifier() or keyword.iskeyword(key):
                raise ValueError(f"Invalid keyword: {key!r}")
            arguments.append(f"{key}={_literal(value)}")
        target = _literal(wells.get(instruction.target, Reference(instruction.target)))
        expression = f"{target}.{instruction.method}({', '.join(arguments)})"
        if instruction.result is not None:
            expression = f"resources[{instruction.result!r}] = {expression}"
        if instruction.skip_during_simulation:
            lines.append("    if not protocol.is_simulating():")
            lines.append(f"        {expression}")
        else:
            lines.append(f"    {expression}")
    return "\n".join(lines) + "\n"
