"""Generate the Sphinx API reference page for BuildCompiler."""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
PACKAGE_ROOT = REPO_ROOT / "src" / "buildcompiler"
OUTPUT_PATH = REPO_ROOT / "docs" / "API_Reference.rst"

SECTION_ORDER = [
    ("Public API", "buildcompiler.api"),
    ("Stages", "buildcompiler.stages"),
    ("Planning", "buildcompiler.planning"),
    ("Inventory", "buildcompiler.inventory"),
    ("SBOL helpers", "buildcompiler.sbol"),
    ("Domain models", "buildcompiler.domain"),
    ("Execution", "buildcompiler.execution"),
    ("Adapters", "buildcompiler.adapters"),
    ("Reporting", "buildcompiler.reporting"),
    ("Legacy modules", "buildcompiler"),
]

LEGACY_MODULES = {
    "buildcompiler.abstract_translator",
    "buildcompiler.buildcompiler",
    "buildcompiler.constants",
    "buildcompiler.plasmid",
    "buildcompiler.robotutils",
    "buildcompiler.sbol2build",
    "buildcompiler.transformation",
}

EXCLUDED_MODULES = {"buildcompiler.__init__"}


def underline(text: str, char: str = "=") -> str:
    return char * len(text)


def module_name(path: Path) -> str:
    relative = path.relative_to(REPO_ROOT / "src").with_suffix("")
    return ".".join(relative.parts)


def discover_modules() -> list[str]:
    modules = []
    for path in sorted(PACKAGE_ROOT.rglob("*.py")):
        name = module_name(path)
        if name.endswith(".__init__") or name in EXCLUDED_MODULES:
            continue
        modules.append(name)
    return modules


def modules_for_section(modules: list[str], package: str) -> list[str]:
    if package == "buildcompiler":
        return [name for name in modules if name in LEGACY_MODULES]
    prefix = f"{package}."
    return [name for name in modules if name.startswith(prefix)]


def render_module(name: str) -> list[str]:
    return [
        name,
        underline(name, "~"),
        "",
        f".. automodule:: {name}",
        "   :members:",
        "   :undoc-members:",
        "   :show-inheritance:",
        "",
    ]


def render_api_reference() -> str:
    modules = discover_modules()
    lines = [
        "API Reference",
        "=============",
        "",
        ".. This file is generated by tools/update_api_reference.py.",
        ".. Run `python tools/update_api_reference.py` after adding or removing public modules.",
        "",
    ]

    for title, package in SECTION_ORDER:
        section_modules = modules_for_section(modules, package)
        if not section_modules:
            continue
        lines.extend([title, underline(title, "-"), ""])
        for name in section_modules:
            lines.extend(render_module(name))

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    OUTPUT_PATH.write_text(render_api_reference(), encoding="utf-8")


if __name__ == "__main__":
    main()
